/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_josehernandez;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author jrdjh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cb_cartas.getModel();
        model.addElement(new Minipekka("Minipekka"));
        model.addElement(new Montapuerco("Montapuerco"));
        model.addElement(new Golem("Golem"));
        model.addElement(new Leñador("Leñador"));
        model.addElement(new Dragon_Infernal("Dragon Ingernal"));
        model.addElement(new Dragon("Dragon"));
        model.addElement(new Gigante_Noble("Gigante Noble"));
        model.addElement(new Pandilla_de_Duendes("Pandilla de Duendes"));
        cb_cartas.setModel(model);

        DefaultComboBoxModel modelCB = (DefaultComboBoxModel) cb_mazos.getModel();
        modelCB.addElement(new Mazo("Mazo1"));
        modelCB.addElement(new Mazo("Mazo2"));
        modelCB.addElement(new Mazo("Mazo3"));
        cb_mazos.setModel(modelCB);


        /*DefaultTreeModel m = (DefaultTreeModel) jt_mazos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode mazo1 = new DefaultMutableTreeNode(new Mazo());
        raiz.add(mazo1);
        DefaultMutableTreeNode mazo2 = new DefaultMutableTreeNode(new Mazo());
        raiz.add(mazo2);
        DefaultMutableTreeNode mazo3 = new DefaultMutableTreeNode(new Mazo());
        raiz.add(mazo3);
        m.reload();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Registrar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_nombreRegistro = new javax.swing.JTextField();
        tf_apellidoRegistro = new javax.swing.JTextField();
        tf_nomUsuarioRegistro = new javax.swing.JTextField();
        pf_contra1Registro = new javax.swing.JPasswordField();
        pf_contra2Registro = new javax.swing.JPasswordField();
        dc_fecha_de_nacimiento = new com.toedter.calendar.JDateChooser();
        bt_color = new javax.swing.JButton();
        bt_registro = new javax.swing.JButton();
        jd_perfil = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tf_nomCarta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_dañoCarta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_ptsVida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cb_cartas = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cb_mazos = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_nomClan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        dc_creacionClan = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        rb_bronce = new javax.swing.JRadioButton();
        rb_plata = new javax.swing.JRadioButton();
        rb_oro = new javax.swing.JRadioButton();
        rb_legendario = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_clanes = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_miembros_del_clan = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_mazos = new javax.swing.JTree();
        bg_tipoClan = new javax.swing.ButtonGroup();
        pop_unirClan = new javax.swing.JPopupMenu();
        jm_unirse = new javax.swing.JMenuItem();
        pop_Arbol = new javax.swing.JPopupMenu();
        jm_info = new javax.swing.JMenuItem();
        jm_modificar = new javax.swing.JMenuItem();
        jd_info = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_info = new javax.swing.JTextArea();
        jd_Modificar = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tf_newName = new javax.swing.JTextField();
        tf_newPtsVida = new javax.swing.JTextField();
        tf_newDaño = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuarioLog = new javax.swing.JTextField();
        pf_contraLog = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("REGISTRAR");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        jLabel7.setText("Nombre de Usuario:");

        jLabel8.setText("Contraseña:");

        jLabel9.setText("Confirmar Contraseña:");

        jLabel10.setText("Fecha de Nacimiento:");

        jLabel11.setText("Color Favorito:");

        bt_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_colorActionPerformed(evt);
            }
        });

        bt_registro.setText("Registrar");
        bt_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_RegistrarLayout = new javax.swing.GroupLayout(jd_Registrar.getContentPane());
        jd_Registrar.getContentPane().setLayout(jd_RegistrarLayout);
        jd_RegistrarLayout.setHorizontalGroup(
            jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_RegistrarLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel4))
                    .addGroup(jd_RegistrarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_apellidoRegistro))
                                    .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_nomUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pf_contra1Registro)))
                            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pf_contra2Registro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(bt_registro))
                            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dc_fecha_de_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jd_RegistrarLayout.setVerticalGroup(
            jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_RegistrarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_apellidoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_nomUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pf_contra1Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pf_contra2Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(dc_fecha_de_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_color, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_RegistrarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28))
                    .addGroup(jd_RegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_registro)))
                .addContainerGap())
        );

        jLabel17.setText("Nombre de la Carta:");

        jLabel18.setText("Daño:");

        jLabel19.setText("Puntos de Vida:");

        jLabel20.setText("Carta");

        jButton4.setText("Crear Carta");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel21.setText("Agregar a:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_cartas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(18, 18, 18)
                                    .addComponent(tf_ptsVida, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_dañoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nomCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jButton4)))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cb_cartas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nomCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cb_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(tf_ptsVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(tf_dañoCarta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("Crear Carta", jPanel1);

        jLabel12.setText("Nombre del Clan:");

        jLabel13.setText("Fecha de Creacion:");

        jLabel14.setText("Tipo:");

        bg_tipoClan.add(rb_bronce);
        rb_bronce.setText("Bronce");

        bg_tipoClan.add(rb_plata);
        rb_plata.setText("Plata");

        bg_tipoClan.add(rb_oro);
        rb_oro.setText("Oro");

        bg_tipoClan.add(rb_legendario);
        rb_legendario.setText("Legendario");

        jButton3.setText("Crear Clan");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dc_creacionClan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_bronce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_plata)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_oro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_legendario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nomClan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jButton3)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nomClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(dc_creacionClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rb_bronce)
                    .addComponent(rb_plata)
                    .addComponent(rb_oro)
                    .addComponent(rb_legendario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(50, 50, 50))
        );

        jTabbedPane1.addTab("Crear Clan", jPanel2);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Clanes");

        jl_clanes.setModel(new DefaultListModel());
        jl_clanes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_clanesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_clanes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Unirse A un Clan", jPanel3);

        jLabel16.setText("Miembros del Clan");

        jl_miembros_del_clan.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_miembros_del_clan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel16)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel16)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clan", jPanel4);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        jt_mazos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_mazos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_mazosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_mazos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mazos", jPanel5);

        javax.swing.GroupLayout jd_perfilLayout = new javax.swing.GroupLayout(jd_perfil.getContentPane());
        jd_perfil.getContentPane().setLayout(jd_perfilLayout);
        jd_perfilLayout.setHorizontalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_perfilLayout.setVerticalGroup(
            jd_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jm_unirse.setText("Unirse Al Clan");
        jm_unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_unirseActionPerformed(evt);
            }
        });
        pop_unirClan.add(jm_unirse);

        jm_info.setText("Informacion");
        jm_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_infoActionPerformed(evt);
            }
        });
        pop_Arbol.add(jm_info);

        jm_modificar.setText("Modificar");
        jm_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_modificarMouseClicked(evt);
            }
        });
        pop_Arbol.add(jm_modificar);

        ta_info.setColumns(20);
        ta_info.setRows(5);
        jScrollPane4.setViewportView(ta_info);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_infoLayout = new javax.swing.GroupLayout(jd_info.getContentPane());
        jd_info.getContentPane().setLayout(jd_infoLayout);
        jd_infoLayout.setHorizontalGroup(
            jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_infoLayout.setVerticalGroup(
            jd_infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_infoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel22.setText("Nuevo Nombre:");

        jLabel23.setText("Nuevos Puntos de Vida:");

        jLabel25.setText("Nuevo Daño:");

        jButton5.setText("Modificar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_ModificarLayout = new javax.swing.GroupLayout(jd_Modificar.getContentPane());
        jd_Modificar.getContentPane().setLayout(jd_ModificarLayout);
        jd_ModificarLayout.setHorizontalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_ModificarLayout.createSequentialGroup()
                        .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_ModificarLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_newPtsVida, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModificarLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(31, 31, 31)
                                .addComponent(tf_newName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_ModificarLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(tf_newDaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(360, 360, 360))))
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_ModificarLayout.setVerticalGroup(
            jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModificarLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tf_newName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tf_newPtsVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jd_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_newDaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(61, 61, 61))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Contraseña:");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Registrar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_usuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_contraLog, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton1)
                        .addGap(71, 71, 71)
                        .addComponent(jButton2)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuarioLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pf_contraLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_colorActionPerformed
        bt_color.setBackground(JColorChooser.showDialog(this, "Ingrese el color", Color.yellow));
    }//GEN-LAST:event_bt_colorActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_Registrar.setModal(true);
        jd_Registrar.pack();
        jd_Registrar.setLocationRelativeTo(this);
        jd_Registrar.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void bt_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registroMouseClicked
        boolean registrado = false;
        String nombre = tf_nombreRegistro.getText();
        String apellido = tf_apellidoRegistro.getText();
        String nomUusario = tf_nomUsuarioRegistro.getText();
        String contraseña1 = pf_contra1Registro.getText();
        String contraseña2 = pf_contra2Registro.getText();
        Date fecha_nacimiento = dc_fecha_de_nacimiento.getDate();
        int edad = (int) (((new Date()).getTime()
                - dc_fecha_de_nacimiento.getDate().getTime())
                / (1000 * 60 * 60 * 24)) / 365;

        Color color_fav = bt_color.getBackground();

        if (nombre.isEmpty() || apellido.isEmpty() || contraseña1.isEmpty()
                || contraseña2.isEmpty()) {
            JOptionPane.showMessageDialog(jd_Registrar, "Alguno de los campos esta Vacio");
        } else if (!contraseña1.equals(contraseña2)) {
            JOptionPane.showMessageDialog(jd_Registrar, "Las contraseñas no coinciden");
        } else {
            lista_usuarios.add(new Usuario(nombre, apellido, nomUusario, contraseña1, fecha_nacimiento, color_fav, edad));
            registrado = true;
            tf_nomUsuarioRegistro.setText("");
            tf_nombreRegistro.setText("");
            tf_apellidoRegistro.setText("");
            pf_contra1Registro.setText("");
            pf_contra2Registro.setText("");
            bt_color.setBackground(Color.red);
            dc_fecha_de_nacimiento.setDate(new Date());
        }

        if (registrado) {
            JOptionPane.showMessageDialog(jd_Registrar, "Registrado Correctamente");
            jd_Registrar.dispose();
        }


    }//GEN-LAST:event_bt_registroMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        String usuarioLog = tf_usuarioLog.getText();
        String contraLog = pf_contraLog.getText();
        for (int i = 0; i < lista_usuarios.size(); i++) {
            if (lista_usuarios.get(i).getNom_usuario().equals(usuarioLog)
                    && lista_usuarios.get(i).getContraseña().equals(contraLog)) {
                usuario_actual = lista_usuarios.get(i);
                jd_perfil.pack();
                jd_perfil.setLocationRelativeTo(this);
                jd_perfil.setVisible(true);
                this.setVisible(false);
                break;

            } else if (!lista_usuarios.get(i).getNom_usuario().equals(usuarioLog)
                    && lista_usuarios.get(i).getContraseña().equals(contraLog)) {
                JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecta");
                break;

            }

        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String nomClan = tf_nomClan.getText();
        Date creacion = dc_creacionClan.getDate();
        String tipo = "";
        if (rb_bronce.isSelected()) {
            tipo = "Bronce";
        } else if (rb_plata.isSelected()) {
            tipo = "Planta";
        } else if (rb_oro.isSelected()) {
            tipo = "Oro";
        } else if (rb_legendario.isSelected()) {
            tipo = "Legendario";
        }

        this.jTabbedPane1.setEnabledAt(2, false);

        lista_clanes.add(new Clan(nomClan, creacion, usuario_actual.getNom_usuario(), tipo, new ArrayList<Usuario>()));
        //se especifica el caln actual.
        clan_actual = new Clan(nomClan, creacion, usuario_actual.getNom_usuario(), tipo, new ArrayList<Usuario>());

        //al clan actual se le agrega a la lista de usuarios un usuario.
        clan_actual.getMiembros().add(usuario_actual);
        DefaultListModel m = (DefaultListModel) jl_clanes.getModel();
        m.addElement(new Clan(nomClan, creacion, usuario_actual.getNom_usuario(), tipo, new ArrayList<Usuario>()));
        jl_clanes.setModel(m);

        DefaultListModel modelo = (DefaultListModel) jl_miembros_del_clan.getModel();
        for (int i = 0; i < clan_actual.getMiembros().size(); i++) {
            modelo.addElement(clan_actual.getMiembros().get(i));
        }

        jl_miembros_del_clan.setModel(modelo);

        tf_nomClan.setText("");
        dc_creacionClan.setDate(new Date());
        rb_bronce.setSelected(true);
        rb_plata.setSelected(false);
        rb_oro.setSelected(false);
        rb_legendario.setSelected(false);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jl_clanesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_clanesMouseClicked
        if (jl_clanes.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                pop_unirClan.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_clanesMouseClicked

    private void jm_unirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_unirseActionPerformed
        DefaultListModel m = (DefaultListModel) jl_clanes.getModel();
        ((Clan) m.get(jl_clanes.getSelectedIndex())).getMiembros().add(usuario_actual);

    }//GEN-LAST:event_jm_unirseActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        int pts_vida = Integer.parseInt(tf_ptsVida.getText());
        String nomCarta = tf_nomCarta.getText();
        double daño = Double.parseDouble(tf_dañoCarta.getText());
        Carta carta = (Carta) cb_cartas.getSelectedItem();
        String tipo = carta.getTipo();
        DefaultTreeModel modelArbol = (DefaultTreeModel) jt_mazos.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelArbol.getRoot();
        DefaultMutableTreeNode nodoCarta = new DefaultMutableTreeNode(carta);
        DefaultMutableTreeNode nodoTipo = new DefaultMutableTreeNode(tipo);
        nodoTipo.add(nodoCarta);
        DefaultMutableTreeNode nodoMazo = new DefaultMutableTreeNode((Mazo) cb_mazos.getSelectedItem());
        nodoMazo.add(nodoTipo);
        raiz.add(nodoMazo);
        modelArbol.setRoot(raiz);
        jt_mazos.setModel(modelArbol);

        tf_nomCarta.setText("");
        tf_dañoCarta.setText("");
        tf_ptsVida.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jt_mazosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_mazosMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_mazos.getClosestRowForLocation(evt.getX(), evt.getY());
            jt_mazos.setSelectionRow(row);
            Object v1 = jt_mazos.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Carta) {
                carta_seleccionada = (Carta) nodo_seleccionado.getUserObject();
                pop_Arbol.show(evt.getComponent(), evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jt_mazosMouseClicked

    private void jm_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_infoActionPerformed
        jd_info.pack();
        jd_info.setLocationRelativeTo(jd_perfil);
        ta_info.append(carta_seleccionada.getObjetivo());
        ta_info.append(carta_seleccionada.getVelocidad());
        ta_info.append("" + carta_seleccionada.getCoste_elixir());
        ta_info.append("" + carta_seleccionada.getPts_vida());

    }//GEN-LAST:event_jm_infoActionPerformed

    private void jm_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_modificarMouseClicked
        jd_Modificar.pack();
        jd_Modificar.setLocationRelativeTo(jd_perfil);
    }//GEN-LAST:event_jm_modificarMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String newName = tf_newName.getText();
        double daño = Double.parseDouble(tf_newDaño.getText());
        int newVida = Integer.parseInt(tf_newPtsVida.getText());
        carta_seleccionada.setNombre(newName);
        carta_seleccionada.setDaño(daño);
        carta_seleccionada.setPts_vida(newVida);
        JOptionPane.showMessageDialog(jd_perfil, "Modificado Exitosamente");
        jd_Modificar.dispose();
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_tipoClan;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_registro;
    private javax.swing.JComboBox<String> cb_cartas;
    private javax.swing.JComboBox<String> cb_mazos;
    private com.toedter.calendar.JDateChooser dc_creacionClan;
    private com.toedter.calendar.JDateChooser dc_fecha_de_nacimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JDialog jd_Modificar;
    private javax.swing.JDialog jd_Registrar;
    private javax.swing.JDialog jd_info;
    private javax.swing.JDialog jd_perfil;
    private javax.swing.JList<String> jl_clanes;
    private javax.swing.JList<String> jl_miembros_del_clan;
    private javax.swing.JMenuItem jm_info;
    private javax.swing.JMenuItem jm_modificar;
    private javax.swing.JMenuItem jm_unirse;
    private javax.swing.JTree jt_mazos;
    private javax.swing.JPasswordField pf_contra1Registro;
    private javax.swing.JPasswordField pf_contra2Registro;
    private javax.swing.JPasswordField pf_contraLog;
    private javax.swing.JPopupMenu pop_Arbol;
    private javax.swing.JPopupMenu pop_unirClan;
    private javax.swing.JRadioButton rb_bronce;
    private javax.swing.JRadioButton rb_legendario;
    private javax.swing.JRadioButton rb_oro;
    private javax.swing.JRadioButton rb_plata;
    private javax.swing.JTextArea ta_info;
    private javax.swing.JTextField tf_apellidoRegistro;
    private javax.swing.JTextField tf_dañoCarta;
    private javax.swing.JTextField tf_newDaño;
    private javax.swing.JTextField tf_newName;
    private javax.swing.JTextField tf_newPtsVida;
    private javax.swing.JTextField tf_nomCarta;
    private javax.swing.JTextField tf_nomClan;
    private javax.swing.JTextField tf_nomUsuarioRegistro;
    private javax.swing.JTextField tf_nombreRegistro;
    private javax.swing.JTextField tf_ptsVida;
    private javax.swing.JTextField tf_usuarioLog;
    // End of variables declaration//GEN-END:variables
    ArrayList<Usuario> lista_usuarios = new ArrayList();
    Usuario usuario_actual;
    Clan clan_actual;
    ArrayList<Clan> lista_clanes = new ArrayList();
    Carta carta_seleccionada;
    DefaultMutableTreeNode nodo_seleccionado;

}
